### ISSUE TITLE
Use Attribute Selectors with Empty Links

### ISSUE THREAD

**Issue by barcia** [barcia/standarize#1]
Display links when the <a> element has no text value but the href attribute has a link:

``` css
a[href^="http"]:empty::before {
  content: attr(href);
}
```
