### ISSUE TITLE
Set font-style: inherit in address

### ISSUE THREAD

**Issue by barcia** [barcia/standarize#19]
Set `font-style: inherit` in `<address>` instead `font-style: italic`

```css
address {
	font-style: inherit;
}
```
