### ISSUE TITLE
Outline: none in anchors

### ISSUE THREAD

**Issue by barcia** [barcia/standarize#9]
```css
/**
 * 1. Remove the outline on focused links when they are also active or hovered
 *    in all browsers.
 */
a:hover,
a:focus,
a:active {
    outline: none; /* 1 */
}
```
